### ISSUE TITLE
Referencing Deleted Function

### ISSUE THREAD

**Issue by wireboy5** [error454/CharacterMovementReplication-UE4#3]
I am trying to run this project, and at compile time I get this error:

'FNetworkPredictionData_Client_Custom::FNetworkPredictionData_Client_Custom(void)': attempting to reference a deleted function

**Comment by error454** [comment]
Sorry about this, this code is a bit old and the engine has changed in the meantime. I think most likely you will have to mimic the prototype found here for the latest engine version:
https://github.com/EpicGames/UnrealEngine/blob/f8f4b403eb682ffc055613c7caf9d2ba5df7f319/Engine/Source/Runtime/Engine/Classes/GameFramework/CharacterMovementComponent.h#L2740
